version: '3.7'

services:
  mariadb:
    container_name: mariadb
    hostname: mariadb
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    ports: 
      - "3306:3306"
    networks:
      - net
    env_file:
      - variables.env

  wordpress:
    container_name: wordpress
    hostname: wordpress
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    depends_on:
      - "mariadb"
    restart: on-failure
    volumes:
      - "wordpress_volume:/var/www/html"
    networks:
      - net
    env_file:
      - variables.env

  nginx:
    container_name: nginx
    hostname: nginx
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    ports:
      - "443:443"
    depends_on:
      - "wordpress"
    volumes:
      - "wordpress_volume:/var/www/html"
    networks:
      - net
    env_file:
      - variables.env

volumes:
  wordpress_volume:
  mariadb_volume:

networks:
  net:
    driver: bridge
