version: '3.7'

services:
  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    ports: 
      - "3306:3306"

  wordpress:
    container_name: wordpress
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    depends_on:
      - "mariadb"
    volumes:
      - "wordpress_volume:/var/www/html"

  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    ports:
      - "443:443"
    depends_on:
      - "wordpress"
    volumes:
      - "wordpress_volume:/var/www/html"

volumes:
  wordpress_volume:
  mariadb_volume: