version: '3.7'

services:
  mariadb:
    container_name: mariadb
    hostname: mariadb
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    ports: 
      - "3306:3306"
    restart: always
    networks:
      - back
    env_file:
      - variables.env
    volumes:
      - "mariadb_volume:/var/run/mysqld"
    command: ["/usr/bin/mysqld_safe"]

  wordpress:
    container_name: wordpress
    hostname: wordpress
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    depends_on:
      - "mariadb"
    restart: always
    volumes:
      - "wordpress_volume:/var/www/html"
    networks:
      - front
      - back
    env_file:
      - variables.env
    command: ["php-fpm7.3", "-F"]

  nginx:
    container_name: nginx
    hostname: nginx
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    ports:
      - "443:443"
    depends_on:
      - "wordpress"
    restart: always
    volumes:
      - "wordpress_volume:/var/www/html"
    networks:
      - front
    env_file:
      - variables.env
    command: ["nginx", "-g", "daemon off;"]

  redis:
    container_name: redis
    hostname: redis
    build:
      context: ./requirements/redis
      dockerfile: Dockerfile
    ports:
      - "6379:6379"
    depends_on:
      - "wordpress"
    restart: always
    volumes:
      - "wordpress_volume:/var/www/html"
    networks:
      - front
    env_file:
      - variables.env
    command: ["redis-server", "--protected-mode no"]

volumes:
  wordpress_volume:
    # driver: "local"
    # driver_opts:
    #   o: bind 
    #   type: "none"
    #   device: /home/mamaurai/data/wordpress
  mariadb_volume:
    # driver: "local"
    # driver_opts:
    #   o: bind 
    #   type: "none"
    #   device: /home/mamaurai/data/mariadb

networks:
  front:
    driver: bridge
  back:
    driver: bridge
