version: '3.7'

services:
  mariadb:
    container_name: mariadb
    hostname: mariadb
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    ports: 
      - "3306:3306"
    restart: always
    networks:
      - back
    env_file:
      - variables.env
    volumes:
      - "mariadb_volume:/var/run/mysqld"
    command: ["/usr/bin/mysqld_safe"]

  wordpress:
    container_name: wordpress
    hostname: wordpress
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    depends_on:
      - "mariadb"
    restart: always
    volumes:
      - "wordpress_volume:/var/www/html"
    networks:
      - front
      - back
    env_file:
      - variables.env
    command: ["php-fpm7.3", "-F"]

  nginx:
    container_name: nginx
    hostname: nginx
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    ports:
      - "443:443"
    depends_on:
      - "wordpress"
    restart: always
    volumes:
      - "wordpress_volume:/var/www/html"
    networks:
      - front
    env_file:
      - variables.env
    command: ["nginx", "-g", "daemon off;"]

  redis:
    container_name: redis
    hostname: redis
    build:
      context: ./requirements/redis
      dockerfile: Dockerfile
    ports:
      - "6379:6379"
    depends_on:
      - "wordpress"
    restart: always
    volumes:
      - "wordpress_volume:/var/www/html"
    networks:
      - front
    env_file:
      - variables.env
    command: ["redis-server", "--protected-mode no"]

  adminer:
    container_name: adminer
    hostname: adminer
    build:
      context: ./requirements/adminer
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - "mariadb"
    restart: always
    volumes:
      - "mariadb_volume:/var/run/mysqld"
    networks:
      - back
    env_file:
      - variables.env
    command: ["php", "-S", "0.0.0.0:8000"]

  vsftpd:
    container_name: vsftpd
    hostname: vsftpd
    build:
      context: ./requirements/vsftpd
      dockerfile: Dockerfile
    ports:
      - "20:20"
      - "21:21"
      - "40000-40009:40000-40009"
    depends_on:
      - "wordpress"
    restart: always
    volumes:
      - "wordpress_volume:/var/www/html"
    networks:
      - front
    env_file:
      - variables.env
    command: ["vsftpd", "/etc/vsftpd.conf"]

  nodejs:
    container_name: nodejs
    hostname: nodejs
    build:
      context: ./requirements/nodejs
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: always
    volumes:
      - "nodejs_volume:/var/www/html/www"
    command: ["npm", "--prefix", "/etc/local/nodejs", "start"]

  portainer:
    container_name: portainer
    hostname: portainer
    build:
      context: ./requirements/portainer
      dockerfile: Dockerfile
    ports:
      - "9443:9443"
    restart: always
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "portainer_volume:/data"
    networks:
      - back
      - front


volumes:
  wordpress_volume:
    # driver: "local"
    # driver_opts:
    #   o: bind 
    #   type: "none"
    #   device: /home/mamaurai/data/wordpress
  mariadb_volume:
    # driver: "local"
    # driver_opts:
    #   o: bind 
    #   type: "none"
    #   device: /home/mamaurai/data/mariadb
  nodejs_volume:
    # driver: "local"
    # driver_opts:
    #   o: bind 
    #   type: "none"
    #   device: /home/mamaurai/data/nodejs
  portainer_volume:
    # driver: "local"
    # driver_opts:
    #   o: bind 
    #   type: "none"
    #   device: /home/mamaurai/data/portainer
    
networks:
  front:
    driver: bridge
  back:
    driver: bridge